### ISSUE TITLE
nested rails app

### ISSUE THREAD

**Issue by nathanallen** [billhimmelsbach/vagabond#7]
You will need to move your rails app up one directory so that it plays nice with heroku. This is a bit tricky, so please see an instructor.

In the future you can create a rails app in the _current_ directory by running: `rails new potato .` <-- Mind the dot

**Comment by billhimmelsbach** [comment]
Thanks! We solved this last night after stumbling around a bit. Natalia and I tested it on an experimental mirrored copy of our repo last night, now we're going to do it for our main repo after we merge all the commits from group members' work last night to avoid conflicts.
